apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-service
  labels:
    app: health-check-service
spec:
  replicas: 3
  template:
    metadata:
      name: health-check-service
      labels:
        app: health-check-service
    spec:
      containers:
        - name: health-check-service
          image:gcr.io/marketplace-sync/health-check-service
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: health-check-service
